name: pytest

on:
  push:
    branches:
      - main

jobs:
  RunTest:
    name: Run pytest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    uses: pavelzw/pytest-action@v2
    with:
      verbose: true
      emoji: true
      job-summary: true
      custom-arguments: '-q'
      click-to-expand: true
      report-title: 'Test Report'